version: '3.9'

services:
  logapi:
    build:
      dockerfile: Dockerfile
      images: fastapi/logapi:main
    ports:
      - "8000:80"
    networks:
      logapi_net:

networks:
  logapi_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: "192.168.0.254"

